#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

authentication_token:
    path: /authentication_token
    methods: ['POST']
swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui